import re

with open('english.tex', 'r') as f:
    content = f.read()

# SPANISH
es_content = content.replace('\\selectlanguage{english}', '\\selectlanguage{spanish}')
es_content = es_content.replace('Computer Engineering', 'Ingeniería Informática')
es_content = es_content.replace('Last updated:', 'Última actualización:')
es_content = es_content.replace('Homepage', 'Página Web')
es_content = es_content.replace('Academic Summary', 'Resumen Académico')
es_content = es_content.replace("I'm currently a Computer Engineering student", "Actualmente soy estudiante de Ingeniería Informática")
es_content = es_content.replace("Academic Background", "Formación Académica")
es_content = es_content.replace("Bachelor in Computer Engineering", "Grado en Ingeniería Informática")
es_content = es_content.replace("Technical Degree in Informatics", "Grado Técnico en Informática")
es_content = es_content.replace("Research Projects", "Proyectos de Investigación")
es_content = es_content.replace("External Courses", "Cursos Externos")
es_content = es_content.replace("Research Interests", "Áreas de Interés")
es_content = es_content.replace("Events", "Eventos")
es_content = es_content.replace("Science Fairs", "Ferias de Ciencias")
es_content = es_content.replace("Conferences", "Congresos")
es_content = es_content.replace("Academic Weeks", "Semanas Académicas")
es_content = es_content.replace("Publications", "Publicaciones")
es_content = es_content.replace("Proceedings", "Actas de Congresos")
es_content = es_content.replace("Articles", "Artículos")
es_content = es_content.replace("Poster", "Póster")
es_content = es_content.replace("Oral Presentation", "Presentación Oral")
es_content = es_content.replace("Talk", "Charla")
es_content = es_content.replace("Brazil", "Brasil")
with open('spanish.tex', 'w') as f:
    f.write(es_content)

# FRENCH
fr_content = content.replace('\\selectlanguage{english}', '\\selectlanguage{french}')
fr_content = fr_content.replace('Computer Engineering', 'Ingénierie Informatique')
fr_content = fr_content.replace('Last updated:', 'Dernière mise à jour:')
fr_content = fr_content.replace('Homepage', 'Site Web')
fr_content = fr_content.replace('Academic Summary', 'Résumé Académique')
fr_content = fr_content.replace("I'm currently a Computer Engineering student", "Je suis actuellement étudiant en ingénierie informatique")
fr_content = fr_content.replace("Academic Background", "Formation Académique")
fr_content = fr_content.replace("Bachelor in Computer Engineering", "Licence en Ingénierie Informatique")
fr_content = fr_content.replace("Technical Degree in Informatics", "Diplôme Technique en Informatique")
fr_content = fr_content.replace("Research Projects", "Projets de Recherche")
fr_content = fr_content.replace("External Courses", "Cours Externes")
fr_content = fr_content.replace("Research Interests", "Centres d'intérêt")
fr_content = fr_content.replace("Events", "Événements")
fr_content = fr_content.replace("Science Fairs", "Foires Scientifiques")
fr_content = fr_content.replace("Conferences", "Conférences")
fr_content = fr_content.replace("Academic Weeks", "Semaines Académiques")
fr_content = fr_content.replace("Publications", "Publications")
fr_content = fr_content.replace("Proceedings", "Actes de Conférences")
fr_content = fr_content.replace("Articles", "Articles")
fr_content = fr_content.replace("Poster", "Affiche")
fr_content = fr_content.replace("Oral Presentation", "Présentation Orale")
fr_content = fr_content.replace("Talk", "Présentation")
fr_content = fr_content.replace("Brazil", "Brésil")
with open('french.tex', 'w') as f:
    f.write(fr_content)

